### ISSUE TITLE
Python setup from scratch

### ISSUE THREAD

**Issue by abhi67srm** [pypa/python-packaging-user-guide#454] opened 2018-03-08 15:30 UTC
As a beginner i faced some problem when I was installing python on my system, like I whether I should install anaconda first then install python or directly I should install  python so these type of problem beginner usually faced when they drive into python from some other programming language, so I want you to explain this issue.
Thank you

**Comment by jonparrott** [comment] 2018-03-08 18:07
Duplicate of #396.

**Closed by jonparrott** 2018-03-08 18:07 UTC
